version: '3'
networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      # - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./resources/js/:/var/www/resources/js/:ro
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    #image: mysql:8.0.29
    build: 
      context: ./dbdata
      dockerfile: Dockerfile
    container_name: mysql-laravel
    ports:
      - "3306:3306"
    volumes:
      - "./dbdata:/var/lyb/mysql"
    restart: always
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - laravel
    depends_on:
      - mysql

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
     - ./:/var/www/
     - laravel-log:/var/www/storage/
     - bootstrap-cache:/var/www/bootstrap/cache/
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    container_name: composer
    image: composer
    command: ["composer","install"]
    depends_on:
      - php
    volumes:
      - ./:/app
    # restart: always
    networks:
      - laravel

volumes:
  laravel-log:
  bootstrap-cache:

